services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /root/diary_bot/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
  bot:
    build:
      context: ./bot
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
